import {ScreenUtils} from '@helpers';
import {Themes} from '@themes';
import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  mainContent: {
    marginTop: ScreenUtils.scale(10),
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: ScreenUtils.scale(4),
    borderColor: Themes.colors.collGray40,
  },
  subContent: {
    padding: ScreenUtils.scale(10),
    flexDirection: 'row',
    alignItems: 'center',
  },
  subContent2: {
    paddingHorizontal: ScreenUtils.scale(10),
    flexDirection: 'row',
    alignItems: 'center',
  },
  choosePlaceStart: {
    flex: 0.9,
    marginLeft: ScreenUtils.scale(8),
    paddingBottom: ScreenUtils.scale(4),
  },
  titleChoosePlaceStart: {
    ...Themes.font.regular,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    color: Themes.colors.coolGray60,
    marginBottom: ScreenUtils.scale(5),
  },
  mainPlaceStart: {
    ...Themes.font.regular,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    color: Themes.colors.blue29,
  },
  subMainPlaceStart: {
    ...Themes.font.regular,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    color: Themes.colors.coolGray60,
    textTransform: 'uppercase',
  },
  arrowUpStyle: {
    position: 'absolute',
    bottom: ScreenUtils.scale(15),
    right: ScreenUtils.scale(15),
  },
  arrowDownStyle: {
    position: 'absolute',
    top: -ScreenUtils.scale(5),
    right: ScreenUtils.scale(15),
  },
  subBottomContent: {
    paddingHorizontal: ScreenUtils.scale(10),
    paddingVertical: ScreenUtils.scale(4),
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Themes.colors.collGray40,
  },
  chooseDateStart: {
    flex: 0.9,
    marginLeft: ScreenUtils.scale(8),
  },
  btnAddMoreStop: {
    marginTop: ScreenUtils.scale(10),
    padding: ScreenUtils.scale(10),
    marginHorizontal: ScreenUtils.scale(30),
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: ScreenUtils.scale(4),
    borderColor: Themes.colors.collGray40,
    backgroundColor: Themes.colors.blue29,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtAddMoreStop: {
    ...Themes.font.medium,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18,
    color: Themes.colors.white,
    marginRight: ScreenUtils.scale(5),
  },
  btnSearch: {
    marginHorizontal: ScreenUtils.scale(16),
    marginTop: ScreenUtils.scale(10),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Themes.colors.collGray40,
    borderRadius: ScreenUtils.scale(4),
    paddingVertical: ScreenUtils.scale(10),
    backgroundColor: Themes.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  txtSearch: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    ...Themes.font.medium,
    color: Themes.colors.white,
    marginLeft: ScreenUtils.scale(4),
  },
  btnClose: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: ScreenUtils.scale(20),
    height: ScreenUtils.scale(20),
    backgroundColor: 'pink',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: ScreenUtils.scale(4),
    borderBottomLeftRadius: ScreenUtils.scale(4),
  },
});
