export const CONSTANT = {
  LANGUAGES: {
    VI: 'vi-VN',
    EN: 'en-US',
    JA: 'ja-JP',
  },
  TOKEN_STORAGE_KEY: {
    ACCESS_TOKEN: 'access_token',
    REFRESH_TOKEN: 'refresh_token',
    TOKEN_TYPE: 'token_type',
    EXPRIES_IN: 'expires_in',
    EXPRIES_AT: 'expires_at',
    LANGUAGE: 'language',
    FIRST_LAUNCH_APP: 'first_launch_app',
  },
  REVOKE_TOKEN_ENDPOINT: 'revocation',
  BASE_URL: 'https://lld-api.datacom.vn',
  TIME_OUT: 300000,
  PATH: {
    login: '/useraccount/login',
    register: '/Agent/Register',
    getTopContent: '/content/gettopcontent',
    getSpecializedNews: '/content/getothercontent',
    getContentByKey: '/content/getbykey',
    getBalanceAgent: '/Agent/GetByKey',
    deleteAccount: '/UserAccount/Delete',
    getOtherContent: '/Content/GetByCategoryId',
    getTopDestination: '/GeoAirport/GetTopDestination',
  },
  PRIVATE_KEY: 'M8jAubpqmKionskikGbQdMBtEBaXI93Hg567XBJUYJkaiqc2jV',
  ID_DEFAULT: '166857de-55d1-4c40-8944-ec3388d4632c',
};
