import {ScreenUtils} from '@helpers';
import {Themes} from '@themes';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Themes.colors.white,
  },
  image: {
    width: '100%',
    height: ScreenUtils.HEIGHT_SCREEN / 1.7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageLogo: {
    position: 'absolute',
    top: ScreenUtils.scale(50),
  },
  mainContent: {
    position: 'absolute',
    top: ScreenUtils.HEIGHT_SCREEN / 2.15,
    width: '100%',
    height: '100%',
    backgroundColor: Themes.colors.white,
    borderTopLeftRadius: ScreenUtils.scale(20),
    borderTopRightRadius: ScreenUtils.scale(20),
    paddingTop: ScreenUtils.scale(20),
    paddingHorizontal: ScreenUtils.scale(24),
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  titleContent: {
    ...Themes.font.medium,
    fontSize: 20,
    lineHeight: 23,
    fontWeight: '700',
    color: Themes.colors.blue29,
    textTransform: 'uppercase',
  },
  subContent: {
    ...Themes.font.medium,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '400',
    color: Themes.colors.black,
    marginTop: ScreenUtils.scale(5),
  },
  textInput: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Themes.colors.collGray40,
    marginTop: ScreenUtils.scale(15),
    paddingVertical: ScreenUtils.scale(12),
    paddingLeft: ScreenUtils.scale(5),
    color: Themes.colors.black,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '400',
    ...Themes.font.medium,
  },
  errorTxt: {
    marginTop: ScreenUtils.scale(2),
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '400',
    color: Themes.colors.red10,
    ...Themes.font.regular,
  },
  rememberAccount: {
    marginTop: ScreenUtils.scale(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtRemember: {
    marginLeft: ScreenUtils.scale(5),
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '400',
    color: Themes.colors.black,
    ...Themes.font.medium,
  },
  btnLogin: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: ScreenUtils.scale(8),
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: ScreenUtils.scale(5),
    paddingHorizontal: ScreenUtils.scale(16),
    backgroundColor: Themes.colors.blue29,
    marginTop: ScreenUtils.scale(16),
    borderColor: Themes.colors.colGray10,
  },
  txtLogin: {
    ...Themes.font.medium,
    fontSize: 14,
    lineHeight: 28,
    fontWeight: '500',
    color: Themes.colors.white,
  },
  txtSuggestRegister: {
    ...Themes.font.regular,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '400',
    color: Themes.colors.black,
    textAlign: 'center',
    marginTop: ScreenUtils.scale(14),
  },
  txtLinkRegister: {
    ...Themes.font.regular,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '400',
    color: Themes.colors.blue29,
  },
  eyeIcon: {
    position: 'absolute',
    right: 0,
    bottom: ScreenUtils.scale(25),
  },
});
