export enum AccountActionType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  CHANGE_LANGUAGE = 'CHANGE_LANGUAGE',
  CHANGE_LANGUAGE_WITH_LAUNCH = 'CHANGE_LANGUAGE_WITH_LAUNCH',
}
